import { Vector2 } from "../vector2";
export declare class Body {
    composition: any;
    position: Vector2;
    mass: number;
    invMass: number;
    inertia: number;
    invInertia: number;
    elasticity: number;
    friction: number;
    angFriction: number;
    maxSpeed: number;
    velocity: Vector2;
    acceleration: Vector2;
    angle: number;
    angVelocity: number;
    layer: number;
    color: string;
    keyForce: number;
    angKeyForce: number;
    up: boolean;
    down: boolean;
    left: boolean;
    right: boolean;
    action: boolean;
    constructor(x?: number, y?: number);
    draw(ctx: any): void;
    update(): void;
    keyControl(): void;
    setColor(color: any): void;
}
